[project]
name = "zadanie4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplot>=0.1.9",
    "numpy>=2.3.5",
    "scipy>=1.16.3",
]
